use crate::events::clipboard::{PollClipboard, get_clipboard};
use crate::events::clone::on_clone;
use crate::events::gravity::on_change_gravity;
use crate::events::hover::{add_hover, remove_hover, spawn_box_select, update_box_select_mesh};
use crate::events::move_up::move_up;
use crate::events::repaint::on_repaint;
use crate::events::roll::on_roll;
use crate::events::scale::on_scale;
use crate::net::{connect_failed, on_connect, on_disconnect};
use bevy::app::App;
pub mod clipboard;
pub mod clone;
pub mod gravity;
pub mod hover;
pub mod move_up;
pub mod repaint;
pub mod roll;
pub mod scale;
pub fn add_events(app: &mut App) {
    app.add_observer(move_up);
    app.add_observer(get_clipboard);
    app.add_observer(on_roll);
    app.add_observer(on_repaint);
    app.add_observer(add_hover);
    app.add_observer(remove_hover);
    app.add_observer(on_clone);
    app.add_observer(on_change_gravity);
    app.add_observer(connect_failed);
    app.add_observer(on_connect);
    app.add_observer(on_disconnect);
    app.add_observer(spawn_box_select);
    app.add_observer(update_box_select_mesh);
    app.add_observer(on_scale);
    app.init_resource::<PollClipboard>();
}
