use crate::chat_commands::react_chat_commands;
use crate::events::clipboard::get_clipboard;
use crate::events::clone::{on_clone, on_clone_objects, on_paste_objects};
use crate::events::delete::on_delete;
use crate::events::gravity::on_change_gravity;
use crate::events::hover::{add_hover, remove_hover, spawn_box_select, update_box_select_mesh};
use crate::events::move_up::move_up;
use crate::events::pile_merge::{on_pile_merge, trigger_pile_merge};
use crate::events::repaint::{on_pile_added, on_pile_removed, on_repaint};
use crate::events::roll::on_roll;
use crate::events::scale::on_scale;
use crate::events::scroll::insert_scroll_bar;
use crate::net::{connect_failed, on_connect, on_disconnect};
use crate::ui::alt_menu::{on_activate_alt_menu, on_remove_alt_menu};
use crate::ui::chat::text_message;
use crate::ui::esc_menu::on_iroh_bind_copy;
use crate::ui::menu::on_set_menu;
use crate::ui::moxfield::{on_moxfield_set_menu, spawn_boards, submit_moxfield};
use crate::ui::right_click::{
    add_copy_menu, ensure_has_menus, ensure_has_menus_post, on_right_click,
    remove_right_click_menus,
};
use crate::ui::side::{
    on_new_search, on_remove_side_menu, on_repaint_side_menu, on_side_hold, on_side_set_menu,
};
use bevy::app::App;
pub mod clipboard;
pub mod clone;
pub mod delete;
pub mod gravity;
pub mod hover;
pub mod move_up;
pub mod pile_merge;
pub mod repaint;
pub mod roll;
pub mod scale;
pub mod scroll;
pub fn add_events(app: &mut App) {
    app.add_observer(move_up);
    app.add_observer(get_clipboard);
    app.add_observer(on_roll);
    app.add_observer(on_repaint);
    app.add_observer(add_hover);
    app.add_observer(remove_hover);
    app.add_observer(on_clone);
    app.add_observer(on_change_gravity);
    app.add_observer(connect_failed);
    app.add_observer(on_connect);
    app.add_observer(on_disconnect);
    app.add_observer(spawn_box_select);
    app.add_observer(update_box_select_mesh);
    app.add_observer(on_scale);
    app.add_observer(react_chat_commands);
    app.add_observer(text_message);
    app.add_observer(insert_scroll_bar);
    app.add_observer(on_delete);
    app.add_observer(on_pile_merge);
    app.add_observer(on_pile_added);
    app.add_observer(on_pile_removed);
    app.add_observer(trigger_pile_merge);
    app.add_observer(on_iroh_bind_copy);
    app.add_observer(on_set_menu);
    app.add_observer(submit_moxfield);
    app.add_observer(spawn_boards);
    app.add_observer(on_repaint_side_menu);
    app.add_observer(on_moxfield_set_menu);
    app.add_observer(on_side_set_menu);
    app.add_observer(on_new_search);
    app.add_observer(on_right_click);
    app.add_observer(add_copy_menu);
    app.add_observer(remove_right_click_menus);
    app.add_observer(on_clone_objects);
    app.add_observer(on_paste_objects);
    app.add_observer(ensure_has_menus);
    app.add_observer(ensure_has_menus_post);
    app.add_observer(on_activate_alt_menu);
    app.add_observer(on_remove_alt_menu);
    app.add_observer(on_side_hold);
    app.add_observer(on_remove_side_menu);
}
