name: lint
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  CARGO_TERM_COLOR: always
jobs:
  lint-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y libwayland-dev libudev-dev libasound2-dev pkg-config
      - name: fmt
        run: cargo fmt --check
      - name: lint
        run: cargo clippy
